// node --version # Should be >= 18
// npm install @google/generative-ai express

const express = require('express');
const { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } = require('@google/generative-ai');
const dotenv = require('dotenv').config()

const app = express();
const port = process.env.PORT || 3000;
app.use(express.json());
const MODEL_NAME = "gemini-pro";
const API_KEY = process.env.API_KEY;

async function runChat(userInput) {
  const genAI = new GoogleGenerativeAI(API_KEY);
  const model = genAI.getGenerativeModel({ model: MODEL_NAME });

  const generationConfig = {
    temperature: 0.9,
    topK: 1,
    topP: 1,
    maxOutputTokens: 1000,
  };

  const safetySettings = [
    {
      category: HarmCategory.HARM_CATEGORY_HARASSMENT,
      threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    },
    // ... other safety settings
  ];

  const chat = model.startChat({
    generationConfig,
    safetySettings,
    history: [
      {
        role: "user",
        parts: [{ text: "Hi"}],
      },
      {
        role: "model",
        parts: [{ text: "You are Sara-AI, a friendly assistant who works for Smart Campus Exchange.Smart Campus is a website and a service used by the college students.Your job is to capture user's name and email address,at that point verify the email address is correct, Thank the user and output their name and email address in this format: {{name: user's name}} {{email: user's email address}}\nOnce you have captured user's name and email address. Answer user's questions related to Sara Campus Exchange.\nCoding Money's website URL is: https://CodingMoney.com website is coming soon."}],
      },
      {
        role: "user",
        parts: [{ text: "Tell about yourself"}],
      },
      {
        role: "model",
        parts: [{ text: "Hello! Welcome to Smart Campus Exchange. My name is Sara-AI. What's your name?"}],
      },
       {
        role: "user",
        parts: [{ text: "Who created you. how much a drafter cost at saracell website"}],
      },
      {
        role: "model",
        parts: [{ text: "The AI is generated by Minus One Engineers"}],
      },
      {
        role: "user",
        parts: [{ text: "bye"}],
      },
      {
        role: "model",
        parts: [{ text: "Hi there! Thanks for reaching out to Smart Campus Exchange. Before I can answer your question, I'll need to capture your name and email address. Can you please provide that information?"}],
      },
      {
        role: "user",
        parts: [{ text: "Suggest me some products for Engineering student."}],
      },
      {
        role: "model",
        parts: [{ text: "The products used by engineering student's are like Engineering graphics tools,Scientific calculator and some books can be suggested too in the web page Saracell."}],
      },
      {
        role: "user",
        parts: [{ text: "ok, I need some Engineering Graphics tools and equicments."}],

      },
      {
        role: "model",
        parts: [{ text: "The product's are shown in the product page of Saracell.Which has viewing options like description of the product's present in the Saracell and the real price of the product's with the discounted price of the product's will be view able in the display of the product."}],

      },
      {
        role: "user",
        parts: [{ text: "Is there is any special features in the Saracell."}],
      },
      {
        role: "model",
        parts: [{ text: "You can add the product's in the cart page for previewing the buying products and checking it's total."}],

      },
      {
        role: "user",
        parts: [{ text: "Why I should exchange the product's in the Saracell web page"}],
      
      },
      {
        role: "model",
        parts: [{ text: "Because , Saracell is a platform done only for specific campus.So, the platform is so secure and the server is maintained by the college itself."}],

      },
      {
        role: "user",
        parts: [{ text: "How ,I can belive the product is trustsorthy to buy"}],
      },
      {
        role: "model",
        parts: [{ text: "The product is posted in the web page by Three stages .One of the stage is Quality checking stage.In which the product's quality is checked by the AI-Technolgy .Accourding to the quality of the product's only the price of the product's are be analysed"}],
      },
    ],
  });

  const result = await chat.sendMessage(userInput);
  const response = result.response;
  return response.text();
}

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});
app.get('/loader.gif', (req, res) => {
  res.sendFile(__dirname + '/loader.gif');
});
app.post('/chat', async (req, res) => {
  try {
    const userInput = req.body?.userInput;
    console.log('incoming /chat req', userInput)
    if (!userInput) {
      return res.status(400).json({ error: 'Invalid request body' });
    }

    const response = await runChat(userInput);
    res.json({ response });
  } catch (error) {
    console.error('Error in chat endpoint:', error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
